### PR TITLE
Fix default values for custom fields

### LINKED ISSUE #91: Default values for custom fields broken
Before

```
$ rclone-v1.30 -h 2>&1| grep chunk-size
      --b2-chunk-size value            Upload chunk size. Must fit in memory. (default 96M)
      --drive-chunk-size value         Upload chunk size. Must a power of 2 >= 256k. (default 8M)
      --dropbox-chunk-size value       Upload chunk size. Max 150M. (default 128M)
      --onedrive-chunk-size value      Above this size files will be chunked - must be multiple of 320k. (default 10M)
      --swift-chunk-size value         Above this size files will be chunked into a _segments container. (default 5G)
```

After

```
$ rclone-v1.33 -h | grep chunk-size
      --b2-chunk-size int               Upload chunk size. Must fit in memory.
      --drive-chunk-size int            Upload chunk size. Must a power of 2 >= 256k.
      --dropbox-chunk-size int          Upload chunk size. Max 150M.
      --onedrive-chunk-size int         Above this size files will be chunked - must be multiple of 320k.
      --swift-chunk-size int            Above this size files will be chunked into a _segments container.
```

No defaults :-(

I've used `git bisect` to discover the problematic commit f90e8bbe4975ae9216a06b7d6f8d33590628e4ab by @moorereason

The above is controlled by a custom value `fs.SizeSuffix`
  * [declaration](https://github.com/ncw/rclone/blob/master/fs/config.go#L54)
  * [methods](https://github.com/ncw/rclone/blob/master/fs/config.go#L133)
  * [use](https://github.com/ncw/rclone/blob/master/b2/b2.go#L77)

See https://github.com/ncw/rclone/issues/706 for background

### PR DESCRIPTION
**Pull request by moorereason**
Fallback to the original default detection logic if we have an unknown
type.

Fixes #91

### CODE REVIEW

File: flag.go [hunk 1]
```diff
@@ -437,7 +437,17 @@ func (f *Flag) defaultIsZeroValue() bool {
 	case *intSliceValue, *stringSliceValue, *stringArrayValue:
 		return f.DefValue == "[]"
 	default:
-		return true
+		switch f.Value.String() {
```
Comment (seh) [inline flag.go:440]: Why does this use `f.Value.String()` instead of `f.DefValue`?

In cases where a caller supplies a value for a custom flag, and that value is not a zero value, this expression yields the wrong result: the _default value_ of the flag is a zero value, but the _set value_ of the flag is not, so the help winds up printing something like
> (default )

per [this line](https://github.com/spf13/pflag/blob/85dd5c8bc61cfa382fecd072378089d4e856579d/flag.go#L735) when it should have omitted mention of a default value.
